
export default function TermsAndConditionsPage() {
  return (
    <>
      <h1>Terms and Conditions</h1>
      <p>Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

      <h2>1. Agreement to Terms</h2>
      <p>
        By using our application, MapMyLED, you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the application.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        MapMyLED provides tools for designing, documenting, and generating configurations for professional LED video walls. The application allows users to create custom pixel maps, define wiring paths, and export configurations for various video processors.
      </p>

      <h2>3. User Responsibilities and Safety</h2>
      <p>
        <strong>Crucial Safety Notice:</strong> The configurations and diagrams generated by MapMyLED are for planning and documentation purposes only. Electrical wiring and hardware setup carry inherent risks, including but not limited to electrical shock, fire, and equipment damage.
      </p>
      <p>
        <strong>You, the user, are solely responsible for verifying all configurations against the official manufacturer's manual and specifications for your specific LED tiles, power supplies, and video processors.</strong> Always follow the safety guidelines, technical specifications, and best practices provided by the hardware manufacturer. Do not rely solely on the output of this application for final implementation.
      </p>

      <h2>4. Intellectual Property</h2>
      <p>
        The Service and its original content, features, and functionality are and will remain the exclusive property of MapMyLED and its licensors.
      </p>

      <h2>5. Limitation of Liability</h2>
      <p>
        In no event shall MapMyLED, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage.
      </p>

      <h2>6. Changes to Terms</h2>
      <p>
        We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms and Conditions on this page.
      </p>

      <h2>7. Contact Us</h2>
      <p>
        If you have any questions about these Terms, please contact us.
      </p>
    </>
  );
}
