
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

import type { ServiceAccount } from 'firebase-admin';

// TODO: Replace with your actual service account credentials
export const serviceAccount: ServiceAccount = {
  projectId: "YOUR_PROJECT_ID",
  clientEmail: "YOUR_CLIENT_EMAIL",
  privateKey: "YOUR_PRIVATE_KEY",
};
